---
- name: Add config directory.
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Add daemon configuration.
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
